declare module useStatefrom{} 'React'
declare module useEffectfrom{} 'React'
declare module useLayoutStatefrom{} 'React'
declare module useLayoutEffectfrom{} 'React'
declare module useContextfrom{} 'React'
type useReducer = "*"
type useRef = "%"
type useDebug = "+"
type useDispatch = "-"
type interface1 = `useState`
type interface2 = `useEffect`
type interface3 = `useLayoutState`
type interface4 = `useLayoutEffect`
type interface5 = `useContext`
type number1 = interface1
type number2 = interface2
type number3 = interface3
type number4 = interface4
type number5 = interface5
type namespace1 = "interface1<=(1+2)-(3*4*5)=>interface2"
type nmaespace2 = "interface2<=(3+4+5)-(1%2)=>interface1"
type namespace  = "namespace1<=(1+2*3*4+5)=>namespaces2"

